const en = {
    translation: {
      channels: {
        channels: 'Channels',
        createChannel: 'Create Channel',
        channelName: 'Channel Name',
        enterName: 'Enter channel name',
        prohibitedName: 'Channel name contains prohibited words',
        addSuccess: 'Channel added successfully',
        addError: 'Error adding channel',
        deleteSuccess: 'Channel deleted successfully',
        deleteError: 'Error deleting channel',
        renameSuccess: 'Channel renamed successfully',
        renameError: 'Error renaming channel',
        rename: 'Rename',
        delete: 'Delete',
        cancel: 'Cancel',
        save: 'Save',
        newName: 'New Name',
        enterNewName: 'Enter new name',
      },
      loading: 'Loading...',
      login: {
        username: 'Username',
        password: 'Password',
        submit: 'Submit',
        signup: 'Sign up',
        newToChat: 'New to chat?',
        authFailed: 'username or password is incorrect',
        header: 'Login',
      },
      modals: {
        add: 'Add channel',
        required: 'Required',
        min: 'Must be 3 to 20 characters',
        max: 'Must be 3 to 20 characters',
        uniq: 'Must be unique',
        cancel: 'Cancel',
        submit: 'Submit',
        remove: 'Remove channel',
        confirmation: 'Are you sure?',
        confirm: 'Confirm',
        rename: 'Rename channel',
        channelName: 'Chanel name',
        editChannelName: 'New channel name',
      },
      hexletChat: 'Hexlet Chat',
      logout: 'Log out',
      chat: {
        send: 'Send',
        messageCount: 'message',
        messageCount_plural: 'messages',
      },
      signup: {
        required: 'Required',
        passMin: 'Min 6 characters',
        mustMatch: 'Passwords must match',
        username: 'Username',
        usernameConstraints: '3 to 20 characters',
        password: 'Password',
        confirm: 'Confirm password',
        alreadyExists: 'Username already taken',
        submit: 'Submit',
        header: 'Signup',
      },
      notFound: {
        header: 'Page not found',
        message: 'You can go ',
        linkText: 'to the main page',
      },
      errors: {
        network: 'Network Error',
        unknown: 'Unknown Error',
      },
    },
  };
  
  export default en;