const ru = {
    translation: {
      channels: {
        channels: 'Каналы',
        createChannel: 'Создать канал',
        channelName: 'Название канала',
        enterName: 'Введите название канала',
        prohibitedName: 'Название канала содержит запрещенные слова',
        addSuccess: 'Канал успешно добавлен',
        addError: 'Ошибка при добавлении канала',
        deleteSuccess: 'Канал удален',
        deleteError: 'Ошибка при удалении канала',
        renameSuccess: 'Канал переименован',
        renameError: 'Ошибка при переименовании канала',
        rename: 'Переименовать',
        delete: 'Удалить',
        cancel: 'Отмена',
        save: 'Сохранить',
        newName: 'Новое название',
        enterNewName: 'Введите новое название',
      },
      loading: 'Загрузка...',
      login: {
        username: 'Ваш ник',
        password: 'Пароль',
        submit: 'Войти',
        signup: 'Регистрация',
        newToChat: 'Нет аккаунта?',
        authFailed: 'Неверные имя пользователя или пароль',
        header: 'Войти',
      },
      modals: {
        add: 'Добавить канал',
        required: 'Обязательное поле',
        min: 'От 3 до 20 символов',
        max: 'От 3 до 20 символов',
        uniq: 'Должно быть уникальным',
        cancel: 'Отменить',
        submit: 'Отправить',
        remove: 'Удалить канал',
        confirmation: 'Уверены?',
        confirm: 'Удалить',
        rename: 'Переименовать канал',
        channelName: 'Имя канала',
        editChannelName: 'Новое имя канала',
      },
      hexletChat: 'Hexlet Chat',
      logout: 'Выйти',
      chat: {
        send: 'Отправить',
        messageCount_zero: 'сообщений',
        messageCount_one: 'сообщение',
        messageCount_few: 'сообщения',
        messageCount_many: 'сообщений',
        newMessage: 'Новое сообщение',
      },
      signup: {
        required: 'Обязательное поле',
        passMin: 'Не менее 6 символов',
        mustMatch: 'Пароли должны совпадать',
        username: 'Имя пользователя',
        usernameConstraints: 'От 3 до 20 символов',
        password: 'Пароль',
        confirm: 'Подтвердите пароль',
        alreadyExists: 'Такой пользователь уже существует',
        submit: 'Зарегистрироваться',
        header: 'Регистрация',
      },
      notFound: {
        header: 'Страница не найдена',
        message: 'Но вы можете перейти ',
        linkText: 'на главную страницу',
      },
      errors: {
        network: 'Ошибка соединения',
        unknown: 'Неизвестная ошибка',
      },
    },
  };
  
  export default ru;